### ISSUE TITLE
Matlab Opensees

### ISSUE THREAD

**Issue by Sadia328** [denavit/OpenSees-Examples#1]
I am trying to run a TCL file using matlab by a command: !Opensees.exe ####.tcl
where ####=tcl file name
I have saved OpenSees.exe file, matlab script m.file and tcl file in same folder but its giving error:
OpenSees.exe' is not recognized as an internal or external command, 
operable program or batch file. 
I also treid running file in opnesees promt but again the same error occured.
Would there be any problem in tcl file or oensees.exe or path?
Please help

**Comment by denavit** [comment]
Is your current working directory the one with OpenSees.exe and the tcl file?

**Comment by Sadia328** [comment]
YES all files are in one folder including m file .

**Comment by Sadia328** [comment]
I even tried using your code for Tcl interaction with matlab. I copy pasted the opensees.exe file in one of your eaxmple folder where there was tcl and batch file and tried running that. I again got same error. Opensees.exe is not recognized....

**Comment by Sadia328** [comment]
![image](https://user-images.githubusercontent.com/70929596/100361286-cc040d80-301b-11eb-8959-31679d73e985.png)

**Comment by Sadia328** [comment]
I checked using a code if tcl file exist or not, it shows it doesnt exist although its in the same folder. 
![image](https://user-images.githubusercontent.com/70929596/100367048-79c6ea80-3023-11eb-863a-5fd911b15ae1.png)

**Comment by denavit** [comment]
Please confirm that your **current working directory** is the one with the files in it. See https://www.mathworks.com/help/matlab/ref/pwd.html

**Comment by Sadia328** [comment]
The current directory  was different, after changing all simple examples are working now except it is not reading the tcl file of simply supported beam downloaded from 
https://opensees.berkeley.edu/wiki/index.php/Simply_supported_beam_modeled_with_two_dimensional_solid_elements
, 
please see the attached file

![image](https://user-images.githubusercontent.com/70929596/100431730-63b83900-30ba-11eb-8779-9faeb32df64f.png)

Thank you very much for sorting my problem. 

,

**Comment by mhscott** [comment]
I would recommend using OpenSeesPy.

**Comment by Sadia328** [comment]
Thank you for your recommendation, I'll try that.

**Comment by Sadia328** [comment]
well, i sorted out by edditing the beam tcl file in PsPad editor, and saving it again in same folder where opensees.exe was. Now its working. Thank you all for your valuable comments.
